
name: Make image config

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_config:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make config for ShokaX config
        run: |
          PersonalWebsite/makeConfig.sh github.sha
