name: Make image config

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

permissions:                    
  contents: write               
  pull-requests: write          

jobs:
  build_config:
    runs-on: ubuntu-latest
    env:
      FILE_STR: "\n"
    steps:
    - uses: actions/checkout@v3            
    - name: Make config for ShokaX config 
      id: make_config
      run: |
        files=$(ls $PWD/PersonalWebsite | grep ".png" | tr -d " ")
        echo $files
        root="https://github.com/kagurazaka-ayano/ImageSource/blob/${{github.sha}}/PersonalWebsite/"
        echo $root
        for file in $files
        do
          echo "- $root$file?raw=true"
          echo "- $root$file?raw=true">> $GITHUB_OUTPUT
        done
    - name: Overwrite file
      uses: "DamianReeves/write-file-action@master"
      with:
        path: PersonalWebsite/config.yml
        write-mode: overwrite
        contents: |
          ${{ steps.make_config.outputs.config }}
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add --all
        git commit -a -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
