name: Make image config

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:



jobs:
  build_config:
    runs-on: ubuntu-latest
    env:
      FILE_STR: "\n"
    steps:
    - uses: actions/checkout@v3            
    - name: Make config for ShokaX config 
      run: |
        files=$(ls $PWD/PersonalWebsite | grep ".png" | tr -d " ")
        echo $files
        root="https://github.com/kagurazaka-ayano/ImageSource/blob/${{github.sha}}/PersonalWebsite/"
        echo $root
        for file in $files
        do
          echo "- $root$file?raw=true"
          echo "- $root$file?raw=true">> ${{ env.FILE_STR }}
        done
    - name: Overwrite file
      uses: "DamianReeves/write-file-action@master"
      with:
        path: $HOME/PersonalWebsite/config.yml
        write-mode: overwrite
        contents: |
          ${{ env.FILE_STR }}
    - name: Commit file
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        git commit -m "Add changes" -a
        echo "::set-output name=push::true"
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
