
name: Make image config

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_config:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make config for ShokaX config
        with:
          command_line: | 
            files=$(ls ${{env.home}}/PersonalWebsite | grep ".png" | tr -d " ")
            root="https://github.com/kagurazaka-ayano/ImageSource/blob/${{github.sha}}/PersonalWebsite/"
            out=${{env.home}}/PersonalWebsite/image.yml
            touch $out
            chmod 777 $out
            > $out
            for file in $files
            do
                echo "- $root$file"
            done
          output_file_name: PersonalWebsite/image.yml
          display_file_content: YES 
