
name: Make image config

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_config:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Make config for ShokaX config
        run: |
          files=$(ls $PWD/PersonalWebsite | grep ".png" | tr -d " ")
          root="https://github.com/kagurazaka-ayano/ImageSource/blob/$1/PersonalWebsite/"
          out=$PWD/PersonalWebsite/image.yml
          touch $out
          chmod 777 $out
          > $out
          for file in $files
          do
              echo "- $root$file" >> $out
          done
